### ISSUE TITLE
1.18.2 startup crash

### ISSUE THREAD

**Issue by Rostas** [mlus-asuka/Thirst-Remade#1]
Minecraft version: 1.18.2
Forge: 40.2.9

[crash-2023-07-06_10.34.30-fml.txt](https://github.com/mlus-asuka/Thirst-Remade/files/11969291/crash-2023-07-06_10.34.30-fml.txt)

**Comment by mlus-asuka** [comment]
Try the newest release in Curse. Updated right now.

**Comment by Rostas** [comment]
Thanks for the fast update but it's crashing due to a few other create mods now.

create-1.18.2-0.5.1.b
createaddition-1.18.2-20230623a
alloyed-1.18.2-v1.5a

[crash-2023-07-06_10.55.56-fml.txt](https://github.com/mlus-asuka/Thirst-Remade/files/11969563/crash-2023-07-06_10.55.56-fml.txt)

![image](https://github.com/mlus-asuka/Thirst-Remade/assets/2160335/31622a7e-4ac2-450a-b78e-cde2978abd16)

**Comment by mlus-asuka** [comment]
uploaded again :p

**Comment by Rostas** [comment]
Thanks, it works. I'll let you know if more issues are found.
