### ISSUE TITLE
walking don't consume thirst

### ISSUE THREAD

**Issue by Edoliviro** [mlus-asuka/Thirst-Remade#3]
i don't know if it wasn't in the original, but walking doesn't consume the thirst bar.

actually the only way to reduce the thirst bar is by jumping and running.

is it a bug or an intended feature?

**Comment by mlus-asuka** [comment]
it comes from the original. What I modified make flying and teleporting don't consume that. I'm not sure whether walking should consume thirst.

**Comment by mlus-asuka** [comment]
New release has been published. It can be enabled in config now.
