### ISSUE TITLE
incompatible of create central kitch

### ISSUE THREAD

**Issue by LENGBAI4775** [mlus-asuka/Thirst-Remade#4]
[latest.log](https://github.com/mlus-asuka/Thirst-Remade/files/12001431/latest.log)
gameversion:1.19.2
modversion:ThirstRemade-1.0.1 ， create_central_kitchen-1.19.2-for-create-0.5.1.b-1.3.8

**Comment by mlus-asuka** [comment]
已发布1.0.2版本
