### ISSUE TITLE
1.0.2存在与其它mod不兼容的未修复bug（丢失纯净度）

### ISSUE THREAD

**Issue by Nech223** [mlus-asuka/Thirst-Remade#5]
1.19.2-Forge_43.2.14
农夫乐事的炉灶、煎锅烧炼脏的陶瓦水碗丢失纯净度。
农夫乐事的煎锅、精妙背包熔炉插件烧炼脏的水瓶得到不可合成的药水，烧炼脏的陶瓦水碗丢失纯净度。
使用更多熔炉模组添加的熔炉出现同样的错误。

mod：
appleskin-forge-mc1.19-2.4.2.jar-苹果皮.jar
AttributeFix-Forge-1.19.2-17.2.6.jar-属性修复.jar
BetterAdvancements-1.19.2-0.3.0.148.jar-更好的进度.jar
BrewinAndChewin-1.19-2.0.jar-饮酒作乐.jar
catalogue-1.7.0-1.19.2.jar-模组目录.jar
configured-2.1.1-1.19.2.jar-配置界面.jar
constructionwand-1.19.2-2.10.jar-建筑手杖.jar
corail_woodcutter-1.19.2-2.5.2.jar
crafting-on-a-stick-1.19.2-1.0.5.jar
craftingtweaks-forge-1.19.2-15.1.7.jar-合成辅助.jar
elevatorid-1.19.2-1.8.9.jar-开放式电梯.jar
expandedstorage-8.3.4+1.19.2-forge.jar-扩展存储.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar-探险者指南针.jar
FarmersDelight-1.19-1.2.1.jar-农夫乐事.jar
FastLeafDecay-30.jar-树叶快速腐烂.jar
ftbbackups2-forge-1.19.2-1.0.17.jar
InventoryProfilesNext-forge-1.19-1.10.6.jar-一键背包整理Next.jar
Jade-1.19.1-forge-8.8.1.jar-玉 ??.jar
jecharacters-1.19.2-4.4.1.jar-通用拼音搜索.jar
jei-1.19.2-forge-11.6.0.1016.jar-JEI物品管理器.jar
lightspeed-1.19.2-1.0.5.jar
moreoverlays-1.21.9-mc1.19.2.jar
MouseTweaks-forge-mc1.19-2.23.jar-鼠标手势.jar
NaturesCompass-1.19.2-1.10.0-forge.jar-自然罗盘／生物群系指南针.jar
NyfsQuiver-1.19.2-0.7.4.jar-Nyf的箭袋.jar
Patchouli-1.19.2-77.jar-帕秋莉手册.jar
raw-ores-processing-1.4.jar
rubidium-0.6.2b.jar-铷.jar
SoL-Carrot-1.19.2-1.14.0.jar-生活调味料：胡萝卜版.jar
sophisticatedbackpacks-1.19.2-3.18.53.868.jar-精妙背包.jar
starlight-1.1.1+forge.cf5b10b.jar-星光.jar
StorageDrawers-1.19-11.1.2.jar-储物抽屉.jar
swingthroughgrass-1.19.2-1.10.0.jar-穿草攻击.jar
ThirstRemade-1.0.2.jar
trashslot-forge-1.19-12.0.2.jar-垃圾槽.jar
XaerosWorldMap_1.30.6_Forge_1.19.1.jar-Xaero的世界地图.jar
Xaeros_Minimap_23.5.0_Forge_1.19.1.jar-Xaero的小地图.jar
[lib-sponge]GunpowderLib-1.19.2-2.1.jar
[lib]architectury-6.5.85-forge.jar
[lib]balm-forge-1.19.2-4.5.7.jar
[lib]cloth-config-8.2.88-forge.jar
[lib]ftb-library-forge-1902.3.19-build.214.jar
[lib]kotlinforforge-3.12.0-all.jar
[lib]libIPN-forge-1.19-3.0.2.jar
[lib]polylib-forge-1900.0.2-build.73.jar
[lib]sophisticatedcore-1.19.2-0.5.77.346.jar-精妙核心.jar
[lib]YungsApi-1.19.2-Forge-3.8.9.jar
[req]curios-forge-1.19.2-5.1.4.1.jar
[方块同步修复] antighost-1.19.1-forge42.0.1-1.1.2.jar
[通用拼音搜索] jecharacters-1.19.2-4.3.7.jar
[键位冲突显示] Controlling-forge-1.19.2-10.0+7.jar

**Comment by mlus-asuka** [comment]
陶瓦水碗忘记写兼容了。确认几个点，农夫乐事的煎锅烧水瓶应该是正常的，更多熔炉烧水瓶应该也是正常的，精妙背包不确定。

**Comment by Nech223** [comment]
> 陶瓦水碗忘记写兼容了。确认几个点，农夫乐事的煎锅烧水瓶应该是正常的，更多熔炉烧水瓶应该也是正常的，精妙背包不确定。

加了更多熔炉（ironfurnaces-1.19.2-3.6.5）测了一下，两个都不正常，煎锅也是不可合成药水。

**Comment by mlus-asuka** [comment]
已修复陶瓦和煎锅。另外两个Mod没有继承Minecraft自带的AbstractFurnace类而是自己写了一套，不兼容是正常的。

**Comment by mlus-asuka** [comment]
已在最新版本重构了配方实现。理论兼容任何Mod。
